declare namespace WorldSimulator2D {
    /**
     * An element definition, typically taken from the periodic table.
     */
    class Element implements IClonable {
        readonly number: number;
        readonly symbol: string;
        readonly name: string;
        readonly color: string;
        readonly standardState: string;
        readonly weight: number;
        readonly density: number;
        readonly boilingPoint: number;
        readonly meltingPoint: number;
        readonly atomicRadius: number;
        readonly ionRadius: number;
        readonly electronAffinity: number;
        readonly electronegativity: number;
        readonly ionizationEnergy: number;
        readonly groupBlock: string;
        readonly freezingPointDepression: number;
        /**
         * Constructs a single element (typically with parameters from the periodic table).
         * @param number The element number in the periodic table (leave this 0 for custom elements).
         * @param name
         * @param weight
         * @param heatCapacity
         * @param boilingPoint
         * @param meltingPoint
         * @param freezingPointDepression
         */
        constructor(number: number, symbol: string, name: string, color: string, standardState: string, weight: number, density: number, boilingPoint: number, meltingPoint: number, atomicRadius: number, ionRadius: number, electronAffinity: number, electronegativity: number, ionizationEnergy: number, groupBlock: string, freezingPointDepression?: number);
        clone(): this;
    }
    namespace PeriodicTable {
        var elements: Element[];
        var Hydrogen: Element;
        var Helium: Element;
        var Lithium: Element;
        var Beryllium: Element;
        var Boron: Element;
        var Carbon: Element;
        var Nitrogen: Element;
        var Oxygen: Element;
        var Fluorine: Element;
        var Neon: Element;
        var Sodium: Element;
        var Magnesium: Element;
        var Aluminum: Element;
        var Silicon: Element;
        var Phosphorus: Element;
        var Sulfur: Element;
        var Chlorine: Element;
        var Argon: Element;
        var Potassium: Element;
        var Calcium: Element;
        var Scandium: Element;
        var Titanium: Element;
        var Vanadium: Element;
        var Chromium: Element;
        var Manganese: Element;
        var Iron: Element;
        var Cobalt: Element;
        var Nickel: Element;
        var Copper: Element;
        var Zinc: Element;
        var Gallium: Element;
        var Germanium: Element;
        var Arsenic: Element;
        var Selenium: Element;
        var Bromine: Element;
        var Krypton: Element;
        var Rubidium: Element;
        var Strontium: Element;
        var Yttrium: Element;
        var Zirconium: Element;
        var Niobium: Element;
        var Molybdenum: Element;
        var Technetium: Element;
        var Ruthenium: Element;
        var Rhodium: Element;
        var Palladium: Element;
        var Silver: Element;
        var Cadmium: Element;
        var Indium: Element;
        var Tin: Element;
        var Antimony: Element;
        var Tellurium: Element;
        var Iodine: Element;
        var Xenon: Element;
        var Cesium: Element;
        var Barium: Element;
        var Lanthanum: Element;
        var Cerium: Element;
        var Praseodymium: Element;
        var Neodymium: Element;
        var Promethium: Element;
        var Samarium: Element;
        var Europium: Element;
        var Gadolinium: Element;
        var Terbium: Element;
        var Dysprosium: Element;
        var Holmium: Element;
        var Erbium: Element;
        var Thulium: Element;
        var Ytterbium: Element;
        var Lutetium: Element;
        var Hafnium: Element;
        var Tantalum: Element;
        var Tungsten: Element;
        var Rhenium: Element;
        var Osmium: Element;
        var Iridium: Element;
        var Platinum: Element;
        var Gold: Element;
        var Mercury: Element;
        var Thallium: Element;
        var Lead: Element;
        var Bismuth: Element;
        var Polonium: Element;
        var Astatine: Element;
        var Radon: Element;
        var Francium: Element;
        var Radium: Element;
        var Actinium: Element;
        var Thorium: Element;
        var Protactinium: Element;
        var Uranium: Element;
        var Neptunium: Element;
        var Plutonium: Element;
        var Americium: Element;
        var Curium: Element;
        var Berkelium: Element;
        var Californium: Element;
        var Einsteinium: Element;
        var Fermium: Element;
        var Mendelevium: Element;
        var Nobelium: Element;
        var Lawrencium: Element;
        var Rutherfordium: Element;
        var Dubnium: Element;
        var Seaborgium: Element;
        var Bohrium: Element;
        var Hassium: Element;
        var Meitnerium: Element;
        var Darmstadtium: Element;
        var Roentgenium: Element;
        var Copernicium: Element;
        var Nihonium: Element;
        var Flerovium: Element;
        var Moscovium: Element;
        var Livermorium: Element;
        var Tennessine: Element;
        var Oganesson: Element;
    }
}
